import { QueryClientProvider, useQuery } from "@tanstack/react-query";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const queryClient = useQuery()
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
        {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
